name: "aws-db-destroy"

on:
#  push:
#    branches: [ "destroy" ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1   

jobs:
  tf-db-destrpu:
    name:  "Terraform Scan Destroy"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    permissions:
        pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Initialize TF
      run: terraform init

    - name: Scan Destroy
      run: terraform destroy -auto-approve